### ISSUE TITLE
Fix encoding problem

### ISSUE THREAD

**Issue by NicMcPhee** [NicMcPhee/edsger#1]
Running the code on a Windows laptop in Firefox in the lab gives the warning:

A form was submitted in the windows-1252 encoding which cannot encode all Unicode characters, so user input may get corrupted. To avoid this problem, the page should be changed so that the form is submitted in the UTF-8 encoding either by changing the encoding of the page itself to UTF-8 or by specifying accept-charset=utf-8 on the form element.

**Comment by lverns** [comment]
Seems like the sort of thing that we could encounter in the (yet unrealized) new implementation, but we'll cross that bridge when we get to it.
