### ISSUE TITLE
Enable Travis-CI

### ISSUE THREAD

**Issue by lverns** [NicMcPhee/edsger#15]
Currently, running the tests requires launching a figwheel REPL, running `(require 'edsger.test-runner)` and then `(edsger.test-runner/run-all-tests)`. It would be nice if we could could set up a runner that could be done from Travis-CI

**Comment by lverns** [comment]
I see that [doo](https://github.com/bensu/doo) 0.1.8 was just released and has support for chrome-headless, so this should be pretty straight forward to get working now.

**Comment by frogrammer** [comment]
Is this issue what you're currently working on?

**Comment by lverns** [comment]
Yep.

**Comment by lverns** [comment]
I've got this working in Travis-CI now. I'll make a PR once I add instructions for running them locally.
